# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
