# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0002_exam_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('seckey', models.CharField(max_length=10)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azmoon.Exam')),
            ],
        ),
    ]
