# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0003_examorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examorder',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='examorder',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
