# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0005_auto_20160922_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='key',
            field=models.CharField(default='1-2 2-3 3-3 4-2', max_length=500),
        ),
    ]
