# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0006_exam_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
