# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0007_auto_20160922_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seckey', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
    ]
