# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0008_examsubmit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSubmit',
            new_name='ExamSubmition',
        ),
    ]
