# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0011_examsubmition_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
