# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0015_auto_20160927_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='school_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='examorder',
            name='school_type',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
