# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0016_auto_20161009_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='city',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='examorder',
            name='provinence',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
