# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0017_auto_20161009_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=0)),
                ('used_flag', models.IntegerField(default=0)),
                ('submition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azmoon.ExamSubmition')),
            ],
        ),
    ]
