# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0018_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='submition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='azmoon.ExamSubmition'),
        ),
    ]
