# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0019_auto_20161013_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='code',
            field=models.CharField(default='notvalid', max_length=10),
        ),
    ]
