# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0021_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
