# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0023_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(default='nothing!', null=True),
        ),
    ]
