# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0026_courseorder_name_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorder',
            old_name='name_name',
            new_name='name',
        ),
    ]
