# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0027_auto_20161013_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseorder',
            name='transaction',
            field=models.CharField(default='not_valid', max_length=20),
        ),
        migrations.AddField(
            model_name='examorder',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examorder',
            name='transaction',
            field=models.CharField(default='not_valid', max_length=20),
        ),
    ]
