# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0028_auto_20161015_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorder',
            old_name='transaction',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='examorder',
            old_name='transaction',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='courseorder',
            name='payed',
            field=models.IntegerField(default=0),
        ),
    ]
