# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0029_auto_20161015_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='parent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='courseorder',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
