# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0030_auto_20161015_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='ordersnumber',
            field=models.IntegerField(default=1),
        ),
    ]
