# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0031_courseorder_ordersnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='should_pay',
            field=models.IntegerField(default=0),
        ),
    ]
