# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0032_courseorder_should_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
