# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0034_auto_20161016_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='examsnumber',
            field=models.IntegerField(default=1),
        ),
    ]
