# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0036_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='used_flag',
        ),
    ]
