# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-20 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0039_auto_20161021_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='examorder',
            name='ordersnumber',
            field=models.IntegerField(default=1),
        ),
    ]
