# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0040_examorder_ordersnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('home_number', models.CharField(max_length=20)),
                ('city', models.CharField(default='unknown', max_length=30)),
                ('provinence', models.CharField(default='unknown', max_length=30)),
                ('parent_phone', models.CharField(max_length=20, null=True)),
                ('orderDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
