# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0041_hotelreserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelreserve',
            old_name='home_number',
            new_name='home_phone',
        ),
        migrations.AddField(
            model_name='hotelreserve',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='azmoon.Course'),
        ),
        migrations.AddField(
            model_name='hotelreserve',
            name='ordersnumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelreserve',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
