# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0042_auto_20161022_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreserve',
            name='session',
            field=models.CharField(default='not valid', max_length=20),
        ),
    ]
