# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmoon', '0043_hotelreserve_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('print_id', models.CharField(default='not_valid', max_length=40)),
            ],
        ),
    ]
